alter table PRUEBA2_MATERIA add constraint FK_PRUEBA2_MATERIA_ON_ESTUDIANTE foreign key (ESTUDIANTE_ID) references PRUEBA2_ESTUDIANTE(ID);
create unique index IDX_PRUEBA2_MATERIA_UK_NOMBRE_MATERIA on PRUEBA2_MATERIA (NOMBRE_MATERIA) where DELETE_TS is null ;
create index IDX_PRUEBA2_MATERIA_ON_ESTUDIANTE on PRUEBA2_MATERIA (ESTUDIANTE_ID);
